name: Exercice2 CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout le code du dépôt
      - name: Récupérer le code du dépôt
        uses: actions/checkout@v4

      # Configuration de Python
      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.5'

      # Installation des dépendances
      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Vérification du formattage avec Black
      - name: Vérifier le formattage avec Black
        run: |
          pip install black
          black --check .

      # Vérification de la qualité du code avec Ruff
      - name: Vérifier la qualité du code avec Ruff
        run: |
          pip install ruff
          ruff .

